from enum import Enum

class LegendCars(Enum):
    _037 = 'L_037.DYN'
    _205_EVO = 'L_205_EVO'
    _205_EVO_2 = 'L_205_EVO_2'
    _206_WRC = 'L_206_WRC'
    ALPINE_A110 = 'L_ALPINE_A110'
    AUDI80 = 'L_AUDI80'
    AUDI80_A1 = 'L_AUDI80_A1'
    C4_WRC = 'L_C4_WRC'
    CELICA = 'L_CELICA'
    COROLLA = 'L_COROLLA'
    DELTA = 'L_DELTA'
    DELTA_4WD = 'L_DELTA_4WD'
    DS3 = 'L_DS3.DYN'
    FIAT131 = 'L_FIAT131'
    FIESTA2017 = 'L_FIESTA2017'
    FOCUS = 'L_FOCUS'
    FORDMKII = 'L_FORDMKII'
    FULVIA = 'L_FULVIA'
    GT3RS = 'L_GT3RS'
    MITSUBISHI_LANCER_EVO_V_1998 = 'L_MITSUBISHI_LANCER_EVO_V_1998'
    POLO = 'L_POLO'
    STRATOS = 'L_STRATOS'
    SUBARU_IMPREZA_S5 = 'L_SUBARU_IMPREZA_S5'
    TOYOTA_YARIS_WRC_2021 = 'L_TOYOTA_YARIS_WRC_2021'
    XSARAWRC = 'L_XSARAWRC'

class WRC1Cars(Enum):
    CITROEN_C3 =  'W1_CITROEN_C3'
    FORD_PUMA = 'W1_FORD_PUMA'
    HYUNDAI_I20 = 'W1_HYUNDAI_I20'
    TOYOTA_YARIS = 'W1_TOYOTA_YARIS'

class WRC2Cars(Enum):
   CITROEN_C3_R5 = 'W2_CITROEN_C3_R5'
   FORD_R5 = 'W2_FORD_R5'
   HYUNDAI_R5 = 'W2_HYUNDAI_R5'
   SKODA_R5 = 'W2_SKODA_R5'
   VOLKSWAGEN_POLO_R5 = 'W2_VOLKSWAGEN_POLO_R5'

class WRCJuniorCars:
    WRCJ_V1 = 'J_WRCJ_V1'
